apiVersion: v1
entries:
  cpln-operator:
  - annotations:
      category: Helm Chart
    apiVersion: v2
    created: "2025-01-31T17:10:38.207314781-05:00"
    description: A Helm chart for the Control Plane Kubernetes Operator
    digest: 46dd833ab5612143da377909aa15f146e71f379f1787fffb94d5fd527f78b60a
    keywords:
    - go
    - Control Plane
    - helm
    maintainers:
    - email: kyle@controlplane.com
      name: Kyle Cupp
    name: cpln-operator
    sources:
    - https://github.com/controlplane-com/k8s-operator
    type: application
    urls:
    - https://controlplane-com.github.io/k8s-operator/chart/cpln-operator-0.1.0.tgz
    version: 0.1.0
generated: "2025-01-31T17:10:38.206564253-05:00"
