image: us-docker.pkg.dev/controlplane/internal/cpln-operator:v0.4.0
env:
  CPLN_API_URL: https://api.cpln.io
  CPLN_WORKLOAD_STATUS_URL: wss://workload-status.cpln.io/register
  WEBHOOK_PORT: 9443
  CONTROLLER_ENABLED: true
  RECONCILE_INTERVAL_SECONDS: 30
  TLS_CERT_DIR: /cert
  TLS_CERT_NAME: tls.crt
  TLS_KEY_NAME: tls.key

  #Set this to restrict the operator to the given kinds. By default, the operator manages all available custom resource kinds
  #MANAGE_KINDS: workload,volumeset