apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
  namespace: controlplane
spec:
  secretName: webhook-cert
  duration: 2160h                     # 90 days
  renewBefore: 360h                   # 15 days
  commonName: operator.controlplane.svc
  dnsNames:
    - operator.controlplane.svc
    - operator.controlplane.svc.cluster.local
  issuerRef:
    name: operator
    kind: Issuer
