kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: controlplane-operator-crds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controlplane-operator-crds
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: controlplane
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controlplane-operator-base
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - delete
      - update
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controlplane-operator-base
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controlplane-operator-base
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: controlplane
---