apiVersion: v1
kind: Service
metadata:
  name: operator
  namespace: controlplane
spec:
  selector:
    app: operator
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: https
              containerPort: 9443
          volumeMounts:
            - name: tls-certs
              mountPath: {{ .Values.env.TLS_CERT_DIR }}
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: webhook-cert
