apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: controlplane-operator
  annotations:
    cert-manager.io/inject-ca-from: "controlplane/webhook-cert"
webhooks:
  - name: webhook.cpln.io
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    matchPolicy: Equivalent
    # Exclude any namespace with skip-webhook=true
    namespaceSelector:
      matchExpressions:
        - key: skip-webhook
          operator: NotIn
          values:
            - "true"
    objectSelector: {}
    clientConfig:
      service:
        name: operator
        namespace: controlplane
        path: /mutate
        port: 443
      # no caBundle needed here; cert-manager will inject it
    rules:
      - apiGroups:   ["cpln.io"]
        apiVersions: ["v1"]
        resources:   ["*"]
        operations:  ["CREATE","UPDATE"]
        scope:       "Namespaced"
      - apiGroups:   [""]
        apiVersions: ["v1"]
        resources:   ["secrets"]
        operations:  ["CREATE","UPDATE"]
        scope:       "Namespaced"
    reinvocationPolicy: Never
