apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deployments.cpln.io
spec:
  group: cpln.io
  names:
    kind: deployment
    plural: deployments
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          kind:
            type: string
          lastModified:
            type: string
          links:
            items:
              properties:
                href:
                  type: string
                rel:
                  type: string
              type: object
            type: array
          name:
            type: string
          org:
            description: The organization that owns the resource
            type: string
          status:
            properties:
              conditions:
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              deploying:
                type: boolean
              endpoint:
                type: string
              expectedDeploymentVersion:
                type: number
              internal:
                type: string
              jobExecutions:
                items:
                  properties:
                    completionTime:
                      type: string
                    conditions:
                      items:
                        properties:
                          lastDetectionTime:
                            type: string
                          lastTransitionTime:
                            type: string
                          message:
                            type: string
                          reason:
                            type: string
                          status:
                            type: string
                          type:
                            type: string
                        type: object
                      type: array
                    containers:
                      additionalProperties:
                        properties:
                          image:
                            type: string
                          message:
                            type: string
                          name:
                            type: string
                          ready:
                            type: boolean
                          resources:
                            properties:
                              cpu:
                                type: number
                              memory:
                                type: number
                              replicas:
                                type: number
                              replicasReady:
                                type: number
                            type: object
                          restarts:
                            properties:
                              count:
                                type: number
                              exitCode:
                                type: number
                              lastRestartTime:
                                type: string
                              reason:
                                type: string
                            type: object
                        type: object
                      type: object
                    name:
                      type: string
                    replica:
                      type: string
                    startTime:
                      type: string
                    status:
                      type: string
                    workloadVersion:
                      type: number
                  type: object
                type: array
              lastProcessedVersion:
                type: number
              message:
                type: string
              operator:
                properties:
                  downstreamOnly:
                    type: boolean
                  healthStatusMessage:
                    type: string
                  lastProcessedGeneration:
                    type: number
                  lastSyncTime:
                    format: datetime
                    type: string
                  lastSyncedGeneration:
                    type: number
                  syncRetries:
                    type: number
                  validationError:
                    type: string
                type: object
              phase:
                type: string
              ready:
                type: boolean
              remote:
                type: string
              versions:
                items:
                  properties:
                    containers:
                      additionalProperties:
                        properties:
                          image:
                            type: string
                          message:
                            type: string
                          name:
                            type: string
                          ready:
                            type: boolean
                          resources:
                            properties:
                              cpu:
                                type: number
                              memory:
                                type: number
                              replicas:
                                type: number
                              replicasReady:
                                type: number
                            type: object
                          restarts:
                            properties:
                              count:
                                type: number
                              exitCode:
                                type: number
                              lastRestartTime:
                                type: string
                              reason:
                                type: string
                            type: object
                        type: object
                      type: object
                    created:
                      type: string
                    gvc:
                      type: number
                    message:
                      type: string
                    name:
                      type: string
                    ready:
                      type: boolean
                    workload:
                      type: number
                  type: object
                type: array
            type: object
        required:
        - org
        type: object
    served: true
    storage: true
    subresources:
      status: {}

