apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.cpln.io
spec:
  group: cpln.io
  names:
    kind: group
    plural: groups
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          created:
            type: string
          description:
            type: string
          id:
            type: string
          identityMatcher:
            properties:
              expression:
                type: string
              language:
                type: string
            type: object
          kind:
            type: string
          lastModified:
            type: string
          links:
            items:
              properties:
                href:
                  type: string
                rel:
                  type: string
              type: object
            type: array
          memberLinks:
            items:
              type: string
            type: array
          memberQuery:
            properties:
              context:
                additionalProperties:
                  type: string
                type: object
              fetch:
                type: string
              kind:
                type: string
              spec:
                properties:
                  match:
                    type: string
                  terms:
                    items:
                      properties:
                        op:
                          type: string
                        property:
                          type: string
                        rel:
                          type: string
                        tag:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                type: object
            type: object
          name:
            type: string
          org:
            description: The organization that owns the resource
            type: string
          origin:
            type: string
          status:
            properties:
              conditions:
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              operator:
                properties:
                  downstreamOnly:
                    type: boolean
                  healthStatusMessage:
                    type: string
                  lastProcessedGeneration:
                    type: number
                  lastSyncTime:
                    format: datetime
                    type: string
                  lastSyncedGeneration:
                    type: number
                  syncRetries:
                    type: number
                  validationError:
                    type: string
                type: object
              phase:
                type: string
            type: object
          tags:
            additionalProperties:
              type: string
            type: object
          version:
            type: number
        required:
        - org
        type: object
    served: true
    storage: true
    subresources:
      status: {}

