apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobexecutionstatuses.cpln.io
spec:
  group: cpln.io
  names:
    kind: jobexecutionstatus
    plural: jobexecutionstatuses
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          completionTime:
            type: string
          conditions:
            items:
              properties:
                lastDetectionTime:
                  type: string
                lastTransitionTime:
                  type: string
                message:
                  type: string
                reason:
                  type: string
                status:
                  type: string
                type:
                  type: string
              type: object
            type: array
          containers:
            additionalProperties:
              properties:
                image:
                  type: string
                message:
                  type: string
                name:
                  type: string
                ready:
                  type: boolean
                resources:
                  properties:
                    cpu:
                      type: number
                    memory:
                      type: number
                    replicas:
                      type: number
                    replicasReady:
                      type: number
                  type: object
                restarts:
                  properties:
                    count:
                      type: number
                    exitCode:
                      type: number
                    lastRestartTime:
                      type: string
                    reason:
                      type: string
                  type: object
              type: object
            type: object
          name:
            type: string
          org:
            description: The organization that owns the resource
            type: string
          replica:
            type: string
          startTime:
            type: string
          status:
            properties:
              conditions:
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              operator:
                properties:
                  downstreamOnly:
                    type: boolean
                  lastProcessedGeneration:
                    type: number
                  lastSyncTime:
                    format: datetime
                    type: string
                  lastSyncedGeneration:
                    type: number
                  syncRetries:
                    type: number
                  validationError:
                    type: string
                type: object
              phase:
                type: string
            type: object
          workloadVersion:
            type: number
        required:
        - org
        type: object
    served: true
    storage: true
    subresources:
      status: {}

