apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: locations.cpln.io
spec:
  group: cpln.io
  names:
    kind: location
    plural: locations
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          created:
            type: string
          description:
            type: string
          id:
            type: string
          kind:
            type: string
          lastModified:
            type: string
          links:
            items:
              properties:
                href:
                  type: string
                rel:
                  type: string
              type: object
            type: array
          name:
            type: string
          org:
            description: The organization that owns the resource
            type: string
          origin:
            type: string
          provider:
            type: string
          region:
            type: string
          spec:
            properties:
              enabled:
                type: boolean
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              geo:
                properties:
                  city:
                    type: string
                  continent:
                    type: string
                  country:
                    type: string
                  lat:
                    type: number
                  lon:
                    type: number
                  state:
                    type: string
                type: object
              ipRanges:
                items:
                  type: string
                type: array
              operator:
                properties:
                  downstreamOnly:
                    type: boolean
                  healthStatusMessage:
                    type: string
                  lastProcessedGeneration:
                    type: number
                  lastSyncTime:
                    format: datetime
                    type: string
                  lastSyncedGeneration:
                    type: number
                  syncRetries:
                    type: number
                  validationError:
                    type: string
                type: object
              phase:
                type: string
            type: object
          tags:
            additionalProperties:
              type: string
            type: object
          version:
            type: number
        required:
        - org
        type: object
    served: true
    storage: true
    subresources:
      status: {}

