apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: persistentvolumestatuses.cpln.io
spec:
  group: cpln.io
  names:
    kind: persistentvolumestatus
    plural: persistentvolumestatuses
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          attributes:
            additionalProperties:
              type: string
            type: object
          currentBytesUsed:
            type: number
          currentSize:
            type: number
          driver:
            type: string
          index:
            type: number
          iops:
            type: number
          lifecycle:
            type: string
          oldStorageDeviceIds:
            items:
              type: string
            type: array
          org:
            description: The organization that owns the resource
            type: string
          resourceName:
            type: string
          status:
            properties:
              conditions:
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              operator:
                properties:
                  downstreamOnly:
                    type: boolean
                  healthStatusMessage:
                    type: string
                  lastProcessedGeneration:
                    type: number
                  lastSyncTime:
                    format: datetime
                    type: string
                  lastSyncedGeneration:
                    type: number
                  syncRetries:
                    type: number
                  validationError:
                    type: string
                type: object
              phase:
                type: string
            type: object
          storageDeviceId:
            type: string
          throughput:
            type: number
          volumeSnapshots:
            items:
              properties:
                created:
                  type: string
                expires:
                  type: string
                id:
                  type: string
                name:
                  type: string
                size:
                  type: number
                tags:
                  items:
                    additionalProperties:
                      type: string
                    type: object
                  type: array
              type: object
            type: array
          zone:
            type: string
        required:
        - org
        type: object
    served: true
    storage: true
    subresources:
      status: {}

