apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.cpln.io
spec:
  group: cpln.io
  names:
    kind: image
    plural: images
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          created:
            type: string
          digest:
            type: string
          id:
            type: string
          kind:
            type: string
          lastModified:
            type: string
          links:
            items:
              properties:
                href:
                  type: string
                rel:
                  type: string
              type: object
            type: array
          manifest:
            additionalProperties:
              type: string
            type: object
          name:
            type: string
          repository:
            type: string
          status:
            properties:
              conditions:
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              operator:
                properties:
                  lastSyncedGeneration:
                    type: number
                type: object
              phase:
                type: string
            type: object
          tag:
            type: string
          tags:
            additionalProperties:
              type: string
            type: object
          version:
            type: number
        type: object
    served: true
    storage: true
    subresources:
      status: {}

