apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policies.cpln.io
spec:
  group: cpln.io
  names:
    kind: policy
    plural: policies
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          bindings:
            items:
              properties:
                permissions:
                  items:
                    type: string
                  type: array
                principalLinks:
                  items:
                    type: string
                  type: array
              type: object
            type: array
          created:
            type: string
          description:
            type: string
          id:
            type: string
          kind:
            type: string
          lastModified:
            type: string
          links:
            items:
              properties:
                href:
                  type: string
                rel:
                  type: string
              type: object
            type: array
          name:
            type: string
          origin:
            type: string
          status:
            properties:
              conditions:
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              operator:
                properties:
                  lastSyncedGeneration:
                    type: number
                type: object
              phase:
                type: string
            type: object
          tags:
            additionalProperties:
              type: string
            type: object
          target:
            type: string
          targetKind:
            type: string
          targetLinks:
            items:
              type: string
            type: array
          targetQuery:
            properties:
              context:
                additionalProperties:
                  type: string
                type: object
              fetch:
                type: string
              kind:
                type: string
              spec:
                properties:
                  match:
                    type: string
                  terms:
                    items:
                      properties:
                        op:
                          type: string
                        property:
                          type: string
                        rel:
                          type: string
                        tag:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                type: object
            type: object
          version:
            type: number
        type: object
    served: true
    storage: true
    subresources:
      status: {}

